INSERT INTO Offers VALUES
( 7, 'sport', NULL, 'THEME'),
( 8, 'film', NULL, 'THEME'),
( 9, 'rozrywka', NULL, 'THEME'),
(10, 'dla dzieci', NULL, 'THEME'),
(11, 'serial', NULL, 'THEME'),
(12, 'muzyka', NULL, 'THEME'),
(13, 'dokument', NULL, 'THEME'),
(14, 'informacje', NULL, 'THEME')
;
INSERT INTO OfferedChannels VALUES
--sport
(7, (SELECT id FROM Channels WHERE name LIKE 'TVP Sport')),
(7, (SELECT id FROM Channels WHERE name LIKE 'POLSAT Sport')),
(7, (SELECT id FROM Channels WHERE name LIKE 'POLSAT Sport Extra')),
(7, (SELECT id FROM Channels WHERE name LIKE 'Eurosport 1')),
(7, (SELECT id FROM Channels WHERE name LIKE 'Eurosport 2')),
(7, (SELECT id FROM Channels WHERE name LIKE 'Extreme Sports Channel')),
(7, (SELECT id FROM Channels WHERE name LIKE 'Eleven')),
(7, (SELECT id FROM Channels WHERE name LIKE 'Eleven Sports')),
(7, (SELECT id FROM Channels WHERE name LIKE 'FightBox')),
(7, (SELECT id FROM Channels WHERE name LIKE 'CANAL+ Sport')),
(7, (SELECT id FROM Channels WHERE name LIKE 'CANAL+ Sport 2')),
(7, (SELECT id FROM Channels WHERE name LIKE 'nSport+')),
(7, (SELECT id FROM Channels WHERE name LIKE 'Motowizja')),
(7, (SELECT id FROM Channels WHERE name LIKE 'Fightklub')),
(7, (SELECT id FROM Channels WHERE name LIKE 'Sportklub')),
--film
(8 ,(SELECT id FROM channels WHERE name like 'TVP 1')),
(8 ,(SELECT id FROM channels WHERE name like 'TVP 2')),
(8 ,(SELECT id FROM channels WHERE name like 'POLSAT')),
(8 ,(SELECT id FROM channels WHERE name like 'TVN')),
(8 ,(SELECT id FROM channels WHERE name like 'TV 4')),
(8 ,(SELECT id FROM channels WHERE name like 'TV Puls')),
(8 ,(SELECT id FROM channels WHERE name like 'TVN 7')),
(8 ,(SELECT id FROM channels WHERE name like 'ATM Rozrywka')),
(8 ,(SELECT id FROM channels WHERE name like 'Stopklatka TV')),
(8 ,(SELECT id FROM channels WHERE name like 'TVP Kultura')),
(8 ,(SELECT id FROM channels WHERE name like 'POLSAT 2')),
(8 ,(SELECT id FROM channels WHERE name like 'Paramount Channel HD')),
(8 ,(SELECT id FROM channels WHERE name like 'POLSAT Film')),
(8 ,(SELECT id FROM channels WHERE name like 'HBO')),
(8 ,(SELECT id FROM channels WHERE name like 'HBO2')),
(8 ,(SELECT id FROM channels WHERE name like 'HBO3')),
(8 ,(SELECT id FROM channels WHERE name like 'Cinemax')),
(8 ,(SELECT id FROM channels WHERE name like 'Cinemax2')),
(8 ,(SELECT id FROM channels WHERE name like 'FilmBox')),
(8 ,(SELECT id FROM channels WHERE name like 'FilmBox Family')),
(8 ,(SELECT id FROM channels WHERE name like 'AXN')),
(8 ,(SELECT id FROM channels WHERE name like 'AXN White')),
(8 ,(SELECT id FROM channels WHERE name like 'AXN Black')),
(8 ,(SELECT id FROM channels WHERE name like 'FOX Comedy')),
(8 ,(SELECT id FROM channels WHERE name like 'POLSAT Romans')),
(8 ,(SELECT id FROM channels WHERE name like 'CBS Europa')),
(8 ,(SELECT id FROM channels WHERE name like 'Kino Polska')),
(8 ,(SELECT id FROM channels WHERE name like 'TNT')),
(8 ,(SELECT id FROM channels WHERE name like 'FOX')),
(8 ,(SELECT id FROM channels WHERE name like 'FilmBox Action')),
(8 ,(SELECT id FROM channels WHERE name like 'FilmBox Arthouse')),
(8 ,(SELECT id FROM channels WHERE name like 'AMC')),
(8 ,(SELECT id FROM channels WHERE name like 'AXN Spin')),
(8 ,(SELECT id FROM channels WHERE name like 'FilmBox Extra HD')),
(8 ,(SELECT id FROM channels WHERE name like 'BBC HD')),
(8 ,(SELECT id FROM channels WHERE name like 'Romance TV')),
(8 ,(SELECT id FROM channels WHERE name like 'TVN Fabuła')),
(8 ,(SELECT id FROM channels WHERE name like 'CBS Action')),
(8 ,(SELECT id FROM channels WHERE name like 'CANAL+')),
(8 ,(SELECT id FROM channels WHERE name like 'CANAL+ Film')),
(8 ,(SELECT id FROM channels WHERE name like 'CANAL+ Family')),
(8 ,(SELECT id FROM channels WHERE name like 'Ale kino+')),
(8 ,(SELECT id FROM channels WHERE name like 'Scifi Universal')),
--rozrywka
(9 ,(SELECT id FROM channels WHERE name like 'TVP 1')),
(9 ,(SELECT id FROM channels WHERE name like 'TVP 2')),
(9 ,(SELECT id FROM channels WHERE name like 'POLSAT')),
(9 ,(SELECT id FROM channels WHERE name like 'TVN')),
(9 ,(SELECT id FROM channels WHERE name like 'TV 4')),
(9 ,(SELECT id FROM channels WHERE name like 'TV Puls')),
(9 ,(SELECT id FROM channels WHERE name like 'TVN 7')),
(9 ,(SELECT id FROM channels WHERE name like 'Polo TV')),
(9 ,(SELECT id FROM channels WHERE name like 'ATM Rozrywka')),
(9 ,(SELECT id FROM channels WHERE name like 'TVP Rozrywka')),
(9 ,(SELECT id FROM channels WHERE name like 'TTV')),
(9 ,(SELECT id FROM channels WHERE name like 'STARS.TV')),
(9 ,(SELECT id FROM channels WHERE name like 'ZOOM TV')),
(9 ,(SELECT id FROM channels WHERE name like 'POLSAT 2')),
(9 ,(SELECT id FROM channels WHERE name like 'POLSAT Play')),
(9 ,(SELECT id FROM channels WHERE name like 'POLSAT Café')),
(9 ,(SELECT id FROM channels WHERE name like 'Food Network HD')),
(9 ,(SELECT id FROM channels WHERE name like 'FOX Comedy')),
(9 ,(SELECT id FROM channels WHERE name like 'POLSAT Romans')),
(9 ,(SELECT id FROM channels WHERE name like '13 Ulica')),
(9 ,(SELECT id FROM channels WHERE name like 'Lifetime')),
(9 ,(SELECT id FROM channels WHERE name like 'Superstacja')),
(9 ,(SELECT id FROM channels WHERE name like 'Travel Channel')),
(9 ,(SELECT id FROM channels WHERE name like 'TVN Turbo')),
(9 ,(SELECT id FROM channels WHERE name like 'TVN Style')),
(9 ,(SELECT id FROM channels WHERE name like 'E! Entertainment')),
(9 ,(SELECT id FROM channels WHERE name like 'TLC')),
(9 ,(SELECT id FROM channels WHERE name like 'BBC Brit')),
(9 ,(SELECT id FROM channels WHERE name like 'TVP Polonia')),
(9 ,(SELECT id FROM channels WHERE name like 'BBC HD')),
(9 ,(SELECT id FROM channels WHERE name like 'Tele 5')),
(9 ,(SELECT id FROM channels WHERE name like 'Mango 24')),
(9 ,(SELECT id FROM channels WHERE name like 'Kuchnia+')),
(9 ,(SELECT id FROM channels WHERE name like 'Domo+')),
--dla dzieci
(10 ,(SELECT id FROM channels WHERE name like 'TVP ABC')),
(10 ,(SELECT id FROM channels WHERE name like 'Disney Channel')),
(10 ,(SELECT id FROM channels WHERE name like 'POLSAT JimJam')),
(10 ,(SELECT id FROM channels WHERE name like 'Disney Junior')),
(10 ,(SELECT id FROM channels WHERE name like 'Cartoon Network')),
(10 ,(SELECT id FROM channels WHERE name like 'Disney XD')),
(10 ,(SELECT id FROM channels WHERE name like 'Nickelodeon')),
(10 ,(SELECT id FROM channels WHERE name like 'Nick Jr.')),
(10 ,(SELECT id FROM channels WHERE name like 'BBC CBeebies')),
(10 ,(SELECT id FROM channels WHERE name like 'Da Vinci Learning')),
(10 ,(SELECT id FROM channels WHERE name like 'MiniMini+')),
(10 ,(SELECT id FROM channels WHERE name like 'teleTOON+')),
(10 ,(SELECT id FROM channels WHERE name like 'Top Kids')),
(10 ,(SELECT id FROM channels WHERE name like 'Boomerang')),
(10 ,(SELECT id FROM channels WHERE name like 'ducktv')),
(10 ,(SELECT id FROM channels WHERE name like 'Baby TV')),
--serial
(11 ,(SELECT id FROM channels WHERE name like 'TVP 1')),
(11 ,(SELECT id FROM channels WHERE name like 'TVP 2')),
(11 ,(SELECT id FROM channels WHERE name like 'POLSAT')),
(11 ,(SELECT id FROM channels WHERE name like 'TVN')),
(11 ,(SELECT id FROM channels WHERE name like 'TV 4')),
(11 ,(SELECT id FROM channels WHERE name like 'TV Puls')),
(11 ,(SELECT id FROM channels WHERE name like 'TVN 7')),
(11 ,(SELECT id FROM channels WHERE name like 'PULS 2')),
(11 ,(SELECT id FROM channels WHERE name like 'TV 6')),
(11 ,(SELECT id FROM channels WHERE name like 'ATM Rozrywka')),
(11 ,(SELECT id FROM channels WHERE name like 'HBO')),
(11 ,(SELECT id FROM channels WHERE name like 'HBO2')),
(11 ,(SELECT id FROM channels WHERE name like 'HBO3')),
(11 ,(SELECT id FROM channels WHERE name like 'AXN')),
(11 ,(SELECT id FROM channels WHERE name like 'AXN White')),
(11 ,(SELECT id FROM channels WHERE name like 'AXN Black')),
(11 ,(SELECT id FROM channels WHERE name like 'FOX Comedy')),
(11 ,(SELECT id FROM channels WHERE name like 'Comedy Central')),
(11 ,(SELECT id FROM channels WHERE name like 'Comedy Central Family')),
(11 ,(SELECT id FROM channels WHERE name like 'FOX')),
(11 ,(SELECT id FROM channels WHERE name like 'TVP Seriale')),
(11 ,(SELECT id FROM channels WHERE name like '13 Ulica')),
(11 ,(SELECT id FROM channels WHERE name like 'BBC HD')),
(11 ,(SELECT id FROM channels WHERE name like 'Sundance Channel')),
(11 ,(SELECT id FROM channels WHERE name like 'Novela tv')),
(11 ,(SELECT id FROM channels WHERE name like 'CBS Action')),
(11 ,(SELECT id FROM channels WHERE name like 'CANAL+ Seriale')),
--muzyka
(12 ,(SELECT id FROM channels WHERE name like 'Eska TV')),
(12 ,(SELECT id FROM channels WHERE name like 'Disco Polo Music')),
(12 ,(SELECT id FROM channels WHERE name like 'TVS')),
(12 ,(SELECT id FROM channels WHERE name like 'MTV Rocks')),
(12 ,(SELECT id FROM channels WHERE name like 'VH1')),
(12 ,(SELECT id FROM channels WHERE name like 'Kino Polska Muzyka')),
(12 ,(SELECT id FROM channels WHERE name like '4FUN.TV')),
(12 ,(SELECT id FROM channels WHERE name like '4FUN HITS')),
(12 ,(SELECT id FROM channels WHERE name like 'VOX')),
(12 ,(SELECT id FROM channels WHERE name like 'MTV Live HD')),
(12 ,(SELECT id FROM channels WHERE name like 'Active Family')),
(12 ,(SELECT id FROM channels WHERE name like 'Power TV')),
(12 ,(SELECT id FROM channels WHERE name like 'Nuta.TV')),
(12 ,(SELECT id FROM channels WHERE name like 'MTV Music')),
--dokument
(13 ,(SELECT id FROM channels WHERE name like 'Fokus TV')),
(13 ,(SELECT id FROM channels WHERE name like 'TVP Historia')),
(13 ,(SELECT id FROM channels WHERE name like 'ID')),
(13 ,(SELECT id FROM channels WHERE name like 'POLSAT Viasat Explore HD')),
(13 ,(SELECT id FROM channels WHERE name like 'POLSAT Viasat History HD')),
(13 ,(SELECT id FROM channels WHERE name like 'BBC Earth')),
(13 ,(SELECT id FROM channels WHERE name like 'National Geographic Channel')),
(13 ,(SELECT id FROM channels WHERE name like 'Discovery Channel')),
(13 ,(SELECT id FROM channels WHERE name like 'Nat Geo Wild')),
(13 ,(SELECT id FROM channels WHERE name like 'Discovery Science')),
(13 ,(SELECT id FROM channels WHERE name like 'Discovery Historia')),
(13 ,(SELECT id FROM channels WHERE name like 'HISTORY')),
(13 ,(SELECT id FROM channels WHERE name like 'CBS Reality')),
(13 ,(SELECT id FROM channels WHERE name like 'H2')),
(13 ,(SELECT id FROM channels WHERE name like 'Nat Geo People HD')),
(13 ,(SELECT id FROM channels WHERE name like 'Animal Planet HD')),
(13 ,(SELECT id FROM channels WHERE name like 'POLSAT Viasat Nature')),
(13 ,(SELECT id FROM channels WHERE name like 'Da Vinci Learning')),
(13 ,(SELECT id FROM channels WHERE name like 'Water Planet')),
(13 ,(SELECT id FROM channels WHERE name like 'CANAL+ Discovery')),
(13 ,(SELECT id FROM channels WHERE name like 'Discovery Life')),
(13 ,(SELECT id FROM channels WHERE name like 'Discovery Turbo Xtra')),
(13 ,(SELECT id FROM channels WHERE name like 'Planete+')),
(13 ,(SELECT id FROM channels WHERE name like 'Viasat History HD/Viasat Nature HD')),
(13 ,(SELECT id FROM channels WHERE name like 'Adventure')),
(13 ,(SELECT id FROM channels WHERE name like 'TVR')),
--informacje
(14 ,(SELECT id FROM channels WHERE name like 'TVP 3')),
(14 ,(SELECT id FROM channels WHERE name like 'TVP Info')),
(14 ,(SELECT id FROM channels WHERE name like 'POLSAT News')),
(14 ,(SELECT id FROM channels WHERE name like 'TVN 24')),
(14 ,(SELECT id FROM channels WHERE name like 'POLSAT News 2')),
(14 ,(SELECT id FROM channels WHERE name like 'TVN 24 Biznes i Świat')),
(14 ,(SELECT id FROM channels WHERE name like 'TV Republika'))
;