// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TV_App.Models;

namespace TV_App.Migrations
{
    [DbContext(typeof(TvAppContext))]
    partial class TvAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TV_App.Models.Channel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<string>("IconUrl")
                        .HasColumnName("icon_url")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Channel");
                });

            modelBuilder.Entity("TV_App.Models.Description", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("content");

                    b.Property<long?>("GuideUpdateId");

                    b.Property<long>("IdProgramme")
                        .HasColumnName("id_programme");

                    b.HasKey("Id");

                    b.HasIndex("Content")
                        .IsUnique();

                    b.HasIndex("GuideUpdateId");

                    b.HasIndex("IdProgramme");

                    b.ToTable("Description");
                });

            modelBuilder.Entity("TV_App.Models.Emission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<long>("ChannelId")
                        .HasColumnName("channel_id");

                    b.Property<long>("ProgrammeId")
                        .HasColumnName("programme_id");

                    b.Property<DateTime>("Start")
                        .HasColumnName("start")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Stop")
                        .HasColumnName("stop")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ProgrammeId");

                    b.HasIndex("Start", "Stop", "ProgrammeId", "ChannelId")
                        .IsUnique();

                    b.ToTable("Emission");
                });

            modelBuilder.Entity("TV_App.Models.Feature", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<long>("Type")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("IND_feature_id");

                    b.HasIndex("Type", "Value")
                        .IsUnique();

                    b.ToTable("Feature");
                });

            modelBuilder.Entity("TV_App.Models.FeatureExample", b =>
                {
                    b.Property<long>("FeatureId")
                        .HasColumnName("feature_id");

                    b.Property<long>("ProgrammeId")
                        .HasColumnName("programme_id");

                    b.HasKey("FeatureId", "ProgrammeId");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("FeatureExample");
                });

            modelBuilder.Entity("TV_App.Models.FeatureTypes", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnName("type_name")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("FeatureTypes");
                });

            modelBuilder.Entity("TV_App.Models.GuideUpdate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<DateTime>("Posted")
                        .HasColumnName("posted")
                        .HasColumnType("datetime");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnName("source")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Posted")
                        .IsUnique();

                    b.ToTable("GuideUpdate");
                });

            modelBuilder.Entity("TV_App.Models.Programme", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<string>("IconUrl")
                        .HasColumnName("icon_url")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("SeqNumber")
                        .HasColumnName("seq_number")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<long?>("SeriesId")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("IND_programme_id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Programme");
                });

            modelBuilder.Entity("TV_App.Models.Rating", b =>
                {
                    b.Property<string>("UserLogin")
                        .HasColumnName("user_login")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<long>("ProgrammeId")
                        .HasColumnName("programme_id");

                    b.Property<long>("RatingValue")
                        .HasColumnName("rating_value");

                    b.HasKey("UserLogin", "ProgrammeId");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("TV_App.Models.Series", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("TV_App.Models.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnName("login")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<double>("WeightActor")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("weight_actor")
                        .HasDefaultValueSql("((0.1))");

                    b.Property<double>("WeightCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("weight_category")
                        .HasDefaultValueSql("((0.3))");

                    b.Property<double>("WeightCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("weight_country")
                        .HasDefaultValueSql("((0.1))");

                    b.Property<double>("WeightDirector")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("weight_director")
                        .HasDefaultValueSql("((0.1))");

                    b.Property<double>("WeightKeyword")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("weight_keyword")
                        .HasDefaultValueSql("((0.3))");

                    b.Property<double>("WeightYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("weight_year")
                        .HasDefaultValueSql("((0.1))");

                    b.HasKey("Login");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TV_App.Models.Description", b =>
                {
                    b.HasOne("TV_App.Models.GuideUpdate", "GuideUpdate")
                        .WithMany("Description")
                        .HasForeignKey("GuideUpdateId");

                    b.HasOne("TV_App.Models.Programme", "IdProgrammeNavigation")
                        .WithMany("Description")
                        .HasForeignKey("IdProgramme")
                        .IsRequired();
                });

            modelBuilder.Entity("TV_App.Models.Emission", b =>
                {
                    b.HasOne("TV_App.Models.Channel", "Channel")
                        .WithMany("Emission")
                        .HasForeignKey("ChannelId")
                        .IsRequired();

                    b.HasOne("TV_App.Models.Programme", "Programme")
                        .WithMany("Emission")
                        .HasForeignKey("ProgrammeId")
                        .IsRequired();
                });

            modelBuilder.Entity("TV_App.Models.Feature", b =>
                {
                    b.HasOne("TV_App.Models.FeatureTypes", "TypeNavigation")
                        .WithMany("Feature")
                        .HasForeignKey("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("TV_App.Models.FeatureExample", b =>
                {
                    b.HasOne("TV_App.Models.Feature", "Feature")
                        .WithMany("FeatureExample")
                        .HasForeignKey("FeatureId")
                        .IsRequired();

                    b.HasOne("TV_App.Models.Programme", "Programme")
                        .WithMany("FeatureExample")
                        .HasForeignKey("ProgrammeId")
                        .IsRequired();
                });

            modelBuilder.Entity("TV_App.Models.Programme", b =>
                {
                    b.HasOne("TV_App.Models.Series", "Series")
                        .WithMany("Programme")
                        .HasForeignKey("SeriesId");
                });

            modelBuilder.Entity("TV_App.Models.Rating", b =>
                {
                    b.HasOne("TV_App.Models.Programme", "Programme")
                        .WithMany("Rating")
                        .HasForeignKey("ProgrammeId")
                        .IsRequired();

                    b.HasOne("TV_App.Models.User", "UserLoginNavigation")
                        .WithMany("Rating")
                        .HasForeignKey("UserLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
